### ISSUE TITLE
20Q4 - Bug Fixes

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-facilities#317]
Round two bug fixes documented in:
#320 
#325
#327
#330
#333
#334

- [x] dcp_colp #322 
```
psql:sql/dcp_colp.sql:886: ERROR:  column "type" does not exist
LINE 695:     WHEN type='OF' THEN 'City Owned'
                   ^
HINT:  Perhaps you meant to reference the column "t.optype".
SELECT 2489
psql:sql/dcp_colp.sql:908: ERROR:  column "name" does not exist
LINE 2: SELECT DISTINCT ON (name, point_location, agency) *
                            ^
HINT:  Perhaps you meant to reference the column "dcp_colp.sname" or the column "dcp_colp_tmp.sname".
```
- [x] doe_lcgms #323 
```
psql:sql/doe_lcgms.sql:99: ERROR:  column "longitude" does not exist
LINE 5:      and longitude is not null 
                 ^
```
- [x] dohmh_daycare
```
psql:sql/dohmh_daycare.sql:157: ERROR:  relation "acs_daycareheadstart" does not exist
LINE 19:         FROM acs_daycareheadstart a, dohmh_daycare d
                      ^
````
- [x] dot_ferryterminals #324 
``` 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "facdb/recipes/dot_ferryterminals.py", line 17, in <module>
    df["address"] = df["name"].apply(quick_clean)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'name'
```

- [x] dot_pedplazas #321 
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1267, in _execute_context
    cursor, statement, context
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 596, in do_execute_no_params
    cursor.execute(statement)
psycopg2.errors.UndefinedTable: relation "dot_pedplazas.latest" does not exist
LINE 1: select st_astext(wkb_geometry) as wkt, * from dot_pedplazas....
                                                      ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "facdb/recipes/dot_pedplazas.py", line 13, in <module>
    sql=f"select st_astext(wkb_geometry) as wkt, * from {table_name}.latest",
  File "/src/facdb/helper/importer.py", line 9, in importer
    df = pd.read_sql(sql, con=facdb_engine)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/sql.py", line 515, in read_sql
    chunksize=chunksize,
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/sql.py", line 1295, in read_query
    result = self.execute(*args)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/sql.py", line 1162, in execute
    *args, **kwargs
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1267, in _execute_context
    cursor, statement, context
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 596, in do_execute_no_params
    cursor.execute(statement)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "dot_pedplazas.latest" does not exist
LINE 1: select st_astext(wkb_geometry) as wkt, * from dot_pedplazas....
                                                      ^

[SQL: select st_astext(wkb_geometry) as wkt, * from dot_pedplazas.latest]
(Background on this error at: http://sqlalche.me/e/13/f405)
psql:sql/dot_pedplazas.sql:21: ERROR:  column "hash" of relation "dot_pedplazas" already exists
```

- [x] dot_publicparking #320
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'facaddress'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "facdb/recipes/dot_publicparking.py", line 17, in <module>
    df["address"] = df["facaddress"].apply(quick_clean)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: 'facaddress'
psql:sql/dot_publicparking.sql:20: ERROR:  column "hash" of relation "dot_publicparking" already exists
UPDATE 44
```
- [x] dpr_parksproperties #319    

```
psql:sql/dpr_parksproperties.sql:67: ERROR:  column "typecatego" does not exist
LINE 14:  factype = typecatego,
                    ^
HINT:  Perhaps you meant to reference the column "t.typecategory".
```
- [x] nysed_activeinstitutions #318
```
psql:sql/nysed_activeinstitutions.sql:24: ERROR:  column "half_k" does not exist
LINE 6:    WHEN (prek::numeric+half_k::numeric+full_k::numeric+gr_1:...
                               ^
HINT:  Perhaps you meant to reference the column "nysed_nonpublicenrollment.halfk".
DROP TABLE
psql:sql/nysed_activeinstitutions.sql:27: ERROR:  relation "nysed_activeinstitutions_tmp" does not exist
LINE 1: ... TABLE nysed_activeinstitutions AS (SELECT * FROM nysed_acti...
                                                             ^
psql:sql/nysed_activeinstitutions.sql:28: ERROR:  table "nysed_activeinstitutions_tmp" does not exist
psql:sql/nysed_activeinstitutions.sql:47: ERROR:  relation "nysed_activeinstitutions" does not exist
psql:sql/nysed_activeinstitutions.sql:203: ERROR:  relation "nysed_activeinstitutions" does not exist
LINE 1: UPDATE nysed_activeinstitutions as t
               ^
psql:sql/nysed_activeinstitutions.sql:226: ERROR:  relation "nysed_activeinstitutions" does not exist
LINE 2: SELECT * FROM nysed_activeinstitutions
                      ^
psql:sql/nysed_activeinstitutions.sql:227: ERROR:  table "nysed_activeinstitutions" does not exist
psql:sql/nysed_activeinstitutions.sql:228: ERROR:  relation "nysed_activeinstitutions_tmp" does not exist
LINE 1: ... TABLE nysed_activeinstitutions AS (SELECT * FROM nysed_acti...
                                                             ^
psql:sql/nysed_activeinstitutions.sql:229: ERROR:  table "nysed_activeinstitutions_tmp" does not exist
```

**Comment by mgraber** [comment]
Round two bug fixes documented in:
#320 
#325
#327
#330

**Comment by SPTKL** [comment]
First round of debugging complete
